version: '3'
services:
  springapp:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vnpay_sandbox
      HOST_URL: http://localhost:8080/
    ports:
      - 8080:8080
#    networks:
#      - backend
    depends_on:
      - db
  db:
    image: postgres:13-alpine
#    container_name: post_gres
#    expose:
#      - 5432
#    ports:
#      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vnpay_sandbox
#    networks:
#      - backend
#networks:
#  backend:
#    name: app
#    driver: bridge