version: '3'
services:
  springapp:
    image: bananeee/sandbox_vnpay_maven_springapp:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vnpay_sandbox
      HOST_URL: https://vnpaysandbox.azurewebsites.net/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vnpay_sandbox
